### ISSUE TITLE
Issue - Plugin_Utils Has no attribute origin_name

### ISSUE THREAD

**Issue by catsizedcoder** [fHDHR/fHDHR_plugin_origin_XUMO#11]
```Checking and Installing Core Dependencies.
[2024-10-27 17:24:49,235] NOOB - Loading  fHDHR v0.9.3-beta, fHDHR_web v0.9.2-beta
[2024-10-27 17:24:50,337] WARNING - XUMO Setup Failed: list index out of range
[2024-10-27 17:24:50,338] ERROR - xumo Origin Setup Failed: OriginSetupError: XUMO Setup Failed
Traceback (most recent call last):
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\main.py", line 38, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 175, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 134, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 40, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\__init__.py", line 50, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\__init__.py", line 19, in __init__
    self.epg = EPG(fhdhr, self.channels, origins)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\epg\__init__.py", line 24, in __init__
    self.epg_method_selfadd()
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\epg\__init__.py", line 378, in epg_method_selfadd
    "class": self.fhdhr.plugins.plugins[plugin_name].Plugin_OBJ(self.channels, self.fhdhr.plugins.plugins[plugin_name].plugin_utils)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\plugins\fHDHR_plugin_origin_XUMO\epg\__init__.py", line 11, in __init__
    self.origin_name = plugin_utils.origin_name
                       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Plugin_Utils' object has no attribute 'origin_name'. Did you mean: 'plugin_name'?
PS C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14> python .\main.py
Checking and Installing Core Dependencies.
[2024-10-27 17:25:40,381] NOOB - Loading  fHDHR v0.9.3-beta, fHDHR_web v0.9.2-beta
[2024-10-27 17:25:41,396] WARNING - XUMO Setup Failed: list index out of range
[2024-10-27 17:25:41,397] ERROR - xumo Origin Setup Failed: OriginSetupError: XUMO Setup Failed
Traceback (most recent call last):
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\main.py", line 38, in <module>
    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 175, in main
    returned_code = start(args, script_dir, fHDHR_web, deps)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 134, in start
    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\cli\run.py", line 40, in run
    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\__init__.py", line 50, in __init__
    self.device = fHDHR_Device(self.fhdhr, self.fhdhr.origins)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\__init__.py", line 19, in __init__
    self.epg = EPG(fhdhr, self.channels, origins)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\epg\__init__.py", line 24, in __init__
    self.epg_method_selfadd()
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\fHDHR\device\epg\__init__.py", line 378, in epg_method_selfadd
    "class": self.fhdhr.plugins.plugins[plugin_name].Plugin_OBJ(self.channels, self.fhdhr.plugins.plugins[plugin_name].plugin_utils)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Cassidy\Downloads\fHDHR-2022-01-14\fHDHR-2022-01-14\plugins\fHDHR_plugin_origin_XUMO-main\epg\__init__.py", line 11, in __init__
    self.origin_name = plugin_utils.origin_name
                       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Plugin_Utils' object has no attribute 'origin_name'. Did you mean: 'plugin_name'?```

I ran into this error upon first startup with the plugin, All Modules installed, I believe it is an issue with the code

**Comment by catsizedcoder** [comment]
I somewhat fixed the issue with it by going back and undoing https://github.com/fHDHR/fHDHR_plugin_origin_XUMO/commit/cf4cffba73b45418de85ff8fdf465de00b41dd50#diff-c72e0870dfd2e32a5efbcf0f50e8f2febf7e95723b418686dd5e04e2dd25da05L11 on my side

**Comment by catsizedcoder** [comment]
Still says list index out of range however Checking and Installing Core Dependencies.
[2024-10-27 17:31:37,380] NOOB - Loading  fHDHR v0.9.3-beta, fHDHR_web v0.9.2-beta
[2024-10-27 17:31:38,104] WARNING - XUMO Setup Failed: list index out of range
[2024-10-27 17:31:38,105] ERROR - xumo Origin Setup Failed: OriginSetupError: XUMO Setup Failed
[2024-10-27 17:31:38,155] NOOB - Running Startup Tasks.
[2024-10-27 17:31:41,468] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.
[2024-10-27 17:31:41,506] NOOB - Updating xumo EPG cache.
[2024-10-27 17:31:41,547] NOOB - Wrote xumo EPG cache. 0 Programs for 0 Channels
[2024-10-27 17:31:41,549] NOOB - Startup Tasks Complete.
[2024-10-27 17:32:17,070] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.
[2024-10-27 17:33:06,110] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.
[2024-10-27 17:33:07,178] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.
[2024-10-27 17:33:07,988] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.
[2024-10-27 17:33:08,812] NOOB - Performing Channel Scan for xumo. This Process can take some time, Please Wait.

**Comment by deathbybandaid** [comment]
Feel free to submit a pull request. Plugins often break due to service api changes.
I have a new baby in my house and probably dont have time for this right now.
